[versions]
# Android Gradle Plugin
androidGradlePlugin = "8.2.1"

# Kotlin
kotlin = "1.9.22"
ksp = "1.9.22-1.0.17"

# AboutLibraries
aboutLibsRelease = "11.1.1"

# Accompanist
accompanist = "0.34.0"

# AndroidX
activityCompose = "1.9.0"
appcompat = "1.7.0"
browser = "1.8.0"
coreKtx = "1.13.1"
datastore = "1.1.1"
espresso = "3.5.1"
lifecycle = "2.8.1"
navigation = "2.7.7"
paging = "3.3.0"
profileinstaller = "1.3.1"
room = "2.6.1"
work = "2.9.0"

# Compose
composeBom = "2024.05.00"
composeCompiler = "1.5.8"
composeHtml = "1.0.2"

# Coil
coil = "2.5.0"

# Hilt
hiltAndroid = "2.50"
hiltCompiler = "1.1.0"
hiltNavigationCompose = "1.1.0"
hiltWork = "1.1.0"

# Miscellaneous Libraries
androidSVG = "1.4"
junit = "4.13.2"
junitExt = "1.1.5"
mockitoCore = "5.11.0"
mockitoJUnitJupiter = "5.11.0"
mockitoKotlin = "5.2.1"
okhttp = "5.0.0-alpha.12"
opmlParser = "3.1.0"
readability4j = "1.0.8"
retrofit2 = "2.9.0"
rome = "1.18.0"
telephoto = "0.7.1"

[libraries]
# AboutLibraries
aboutlibraries-core = { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "aboutLibsRelease" }
aboutlibraries-compose = { group = "com.mikepenz", name = "aboutlibraries-compose-m3", version.ref = "aboutLibsRelease" }

# Compose
compose-html = { group = "com.github.ireward", name = "compose-html", version.ref = "composeHtml" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }

# Accompanist
accompanist-swiperefresh = { group = "com.google.accompanist", name = "accompanist-swiperefresh", version.ref = "accompanist" }

# Coil
coil-base = { group = "io.coil-kt", name = "coil-base", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil" }

# Hilt
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWork" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltAndroid" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltCompiler" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# AndroidX
android-svg = { group = "com.caverock", name = "androidsvg-aar", version.ref = "androidSVG" }
opml-parser = { group = "be.ceau", name = "opml-parser", version.ref = "opmlParser" }
readability4j = { group = "net.dankito.readability4j", name = "readability4j", version.ref = "readability4j" }
rome = { group = "com.rometools", name = "rome", version.ref = "rome" }
telephoto = { group = "me.saket.telephoto", name = "zoomable", version.ref = "telephoto" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-coroutines = { group = "com.squareup.okhttp3", name = "okhttp-coroutines-jvm", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit2" }
profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
room-common = { group = "androidx.room", name = "room-common", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
paging-common-ktx = { group = "androidx.paging", name = "paging-common-ktx", version.ref = "paging" }
paging-runtime-ktx = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-ext = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
mockito-junit-jupiter = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockitoJUnitJupiter" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibsRelease" }
room = { id = "androidx.room", version.ref = "room" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }