name: "Build Pull Request"
on: pull_request

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.3.0
            - uses: actions/setup-java@v3.10.0
              with:
                  distribution: temurin
                  java-version: 17

            - uses: gradle/gradle-build-action@v2.4.2
            - run: gradle assembleGithubRelease

            - uses: actions/upload-artifact@v3.1.1
              with:
                  name: github-${{ github.sha }}
                  path: app/build/outputs/apk/github/release/*.apk
            - uses: actions/upload-artifact@v3
              with:
                  name: fdroid-${{ github.sha }}
                  path: app/build/outputs/apk/fdroid/release/*.apk
